VwM/Controllers/DeviceController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Localization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Localization;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Options;
using AutoMapper;
using VwM.Database.Models;
using VwM.Database.Collections;
using VwM.Database.Filters;
using VwM.ViewModels;

namespace VwM.Controllers
{
    [Authorize]
    public class DeviceController : MyController<DeviceController>
    {
        private readonly DeviceCollection _devices;
        private readonly IMapper _mapper;


        public DeviceController(
            ILogger<DeviceController> logger,
            IStringLocalizer<DeviceController> localizer,
            DeviceCollection devices,
            IMapper mapper) : base(logger, localizer)
        {
            _devices = devices;
            _mapper = mapper;
        }


        [HttpGet]
        public IActionResult List() => View();


        [HttpGet]
        public IActionResult New() => View("Form", new DeviceViewModel());


        [HttpGet]
        public async Task<IActionResult> Edit(string id)
        {
            if (string.IsNullOrWhiteSpace(id))
                return BadRequest();

            var entry = await _devices.GetFirstOrDefaultAsync(a => a.Id == id);

            if (entry == null)
                return NotFound();

            var model = _mapper.Map<DeviceViewModel>(entry);

            return View("Form", model);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Save(DeviceViewModel model)
        {
            if (!ModelState.IsValid)
                return View("Form", model);

            try
            {
                if (string.IsNullOrWhiteSpace(model.Id))
                {
                    // Insert
                    var entry = _mapper.Map<Device>(model);
                    await _devices.InsertOneAsync(entry);
                    model.Id = entry.Id;
                }
                else
                {
                    // Update
                    var entry = await _devices.GetFirstOrDefaultAsync(a => a.Id == model.Id);

                    if (entry == null)
                        return NotFound();

                    _mapper.Map(model, entry);
                    var result = await _devices.ReplaceOneAsync(a => a.Id == model.Id, entry);

                    if (result.MatchedCount != 1)
                        return NotFound();
                }
            }
            catch (Exception e)
            {
                ModelState.AddModelError("", e.Message);
                return View("Form", model);
            }

            return RedirectToAction("List");
        }
    }
}

VwM/Controllers/ToolController.cs
using System;
using System.Linq;
using System.Collections.Generic;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Localization;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.DependencyInjection;
using VwM.Database.Collections;
using VwM.ViewModels;
using VwM.BackgroundServices;
using VwM.Database.Server;
using AutoMapper;

namespace VwM.Controllers
{
    [Authorize]
    public partial class ToolController : MyController<ToolController>
    {
        private readonly PingRequestQueue _pingQueue;
        private readonly WhoisRequestQueue _whoisQueue;
        private readonly DeviceCollection _devices;
        private readonly WhoisCollection _whois;
        private readonly ToolListViewModel _listModel;
        private readonly DatabaseStatus _dbStatus;
        private readonly IMapper _mapper;


        public ToolController(
            ILogger<ToolController> logger,
            IStringLocalizer<ToolController> localizer,
            DeviceCollection devices,
            WhoisCollection whoisCollection,
            PingRequestQueue pingQueue,
            WhoisRequestQueue whoisQueue,
            ToolListViewModel listModel,
            DatabaseStatus databaseStatus,
            IMapper mapper) : base(logger, localizer)
        {
            _devices = devices;
            _whois = whoisCollection;
            _pingQueue = pingQueue;
            _whoisQueue = whoisQueue;
            _listModel = listModel;
            _dbStatus = databaseStatus;
            _mapper = mapper;
        }


        [HttpGet]
        public IActionResult List() => View(_listModel);
    }
}

VwM/Views/Shared/_FormValidation.cshtml
@using Microsoft.AspNetCore.Mvc.Localization
@inject IViewLocalizer Lcz
@{ 
    var modelOnly = Html.ViewData.ModelState.Where(x => x.Key == "");
}
@if (!ViewData.ModelState.IsValid && modelOnly.Any())
{
    <div class="alerts">
        @foreach (var e in modelOnly.SelectMany(kv => kv.Value.Errors))
        {
            <div class="alert alert-danger mb-2">@e.ErrorMessage</div>
        }
        <div class="text-right">
            <a class="vwm-close" data-dismiss="alerts">@Lcz["ClearAll"]</a>
        </div>
    </div>
}

VwM/Views/Shared/_Layout.cshtml
@using System.Globalization
@using Microsoft.AspNetCore.Builder
@using Microsoft.Extensions.Options
@using Microsoft.AspNetCore.Mvc.Localization
@using VwM.Extensions
@inject IViewLocalizer Lcz
@inject IOptions<RequestLocalizationOptions> LocOptions
@{
    var language = CultureInfo.CurrentCulture.TwoLetterISOLanguageName;
    var cultureItems = LocOptions.Value.SupportedUICultures
        .Select(c => new SelectListItem {
            Value = c.Name,
            Text = c.NativeName.ToUpperFirst(),
            Selected = language == c.TwoLetterISOLanguageName })
        .ToList();
}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] | VwM</title>
    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
    @RenderSection("Styles", required:false)
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">VwM</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse"
                        aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        @if (User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark has-hover-underline" asp-controller="Device" asp-action="List">
                                    @Lcz["Devices"]
                                </a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark has-hover-underline" asp-controller="Tool" asp-action="List">
                                    @Lcz["Tools"]
                                </a>
                            </li>
                            <li class="nav-item ml-auto">
                                <a class="nav-link text-dark has-hover-underline" asp-controller="Home" asp-action="Logout">
                                    @Lcz["Logout"]
                                </a>
                            </li>
                        }
                        else
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark has-hover-underline" asp-controller="Home" asp-action="Login">
                                    @Lcz["SignIn"]
                                </a>
                            </li>
                        }
                    </ul>
                </div>
                <div id="language" data-value="@language">
                    <form asp-controller="Home" asp-action="SetLanguage" asp-antiforgery="false"
                          asp-route-returnUrl="@Context.Request.Path">
                        <select name="culture"
                                class="custom-select custom-select-sm form-control form-control-sm"
                                onchange="this.form.submit();"
                                asp-items="cultureItems"></select>
                    </form>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2019@(DateTime.Now.Year == 2019 ? "" : "-" + DateTime.Now.Year) Vitaliy V. Tokarev
        </div>
    </footer>
    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
        <script src="~/js/site.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="~/lib/jquery/dist/jquery.min.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>
    @RenderSection("Scripts", required: false)
</body>
</html>